language: java
jdk:
- openjdk8
notifications:
  email:
    on_success: never
    on_failure: always
  slack:
    secure: UW1NBLkywVypP4ZmZsWpRe2evVtiheLeDcot9Y6se0xeE0uGAn5VHwgYI3i6to8trWOcUzkWF//M0WUHdLPHYzVfDUKXI7naNKX1lvc5mOaJyt8bzqLZTB68rX0/Lu0eYPrKRZAOfrVYpG3F3gbiO3Cc10hdED4peqrPM3n6M5Nv4VL56XzFLjfdORT0K3I9DpJY00enLey5Uk/KyPFChIYp3wdBoPKa2n/7kofeJ9AdfI/RrDAcK73uYdoRJptiwKZBT8QsXFRHKE5H4xyg5GyZMUpD0+4wMSVKCBBit+ffu8Gn24pw/orGD1t7Oydozsfucw0rer/5YTJ03Ub4C3J8FwEGK4d4ub51iCnLoef68m7blwsiQNtrVTDSOBYMsO2WbM4L5IHk9IU8lVDNGc3BjED8EvElJvtTEg/JHTPBBeXDAnM7oIlM+qJxpJhEtCxHGBfkf+6waGRk4tvc3X8cJQ4FApbRoUYqJdRZQMihJ2kjiBCgX5kVfT0qRaMUoLpMw5K5wLnWzDERxICbaTh96zrYvFqL55p7gtVa2cfbG8cGiyhsldIwVsWyrF/vEBzIKDYeNmpLcEK5pcKIIvTrZNSFIKlvTESeTE2tOnzSZ6UDMbjKiouLAyui++Xp9BZIdCvIG0wiQ91TdCSUbOOop2pNpufZW+WwoaxlXr8=
    on_success: always
    on_failure: always
