# MQ connection information -------------------------------
qmgrConnectionParams:
# Queue manager name.
  qmgrName: QM
# Queue manager host.
  qmgrHost: hostname
# Queue manager connection port.
  qmgrPort: 1414
# Queue manager connection channel.
  qmgrChannel: SYSTEM.DEF.SVRCONN
# Username, which will be used for connection (optional).
# User must have permission to subscribe to the topic $SYS/MQ/INFO/QMGR/QM/Monitor/ and all subtopics.
# User also must have permission to inquire  channels, queues and listeners listed below in Monitoring objects section! 
  user: mqm
# Password, which will be used for connection (optional).
  password: mqm
# Use MQCSP for connection?
  mqscp: false

# Prometheus connection information -------------------------------
prometheusEndpointParams:
# URL and port which will be used to expose metrics for Prometheus.
  url: /metrics
  port: 8080


# Monitoring objects ----------------------------------
# This block refers to collecting of additional metrics.
# If there are any queues, channels or listeners in the config file below,
# these metrics may be useful for you. (More info about additional metrics is located 
# under "MQ PCF API specific statistics" section.   
PCFParameters:
# Collect additional metrics? If false, all settings in this section below are ignored. 
# If yes, additional metrics will be collected for all queues, channels and listeners listed below. 
  sendPCFCommands: true
# If usePCFWildcards equals "true", then all monitored objects will be grouped by object type:
# QUEUE, CHANNEL and LISTENER. Only one PCF command will be send for each object type.
# Metrics will be obtained from the PCF command response for each object one type.
# If usePCFWildcards equals "false", then PCF command will be send for each object.
# PCF command are sent in one connection to MQ queue manager, so for many PCF command will be opened many connection to MQ queue manager.
# For example, for 100 monitoring queue will be opened 100 connection to MQ queue manager, if usePCFwildcard equals "false".
  usePCFWildcards: true
# Interval in seconds between sending PCF commands.
  scrapeInterval: 10

# Monitored queues.
queues:
  - QUEUE1
  - QUEUE2

# Monitored listeners.
listeners:
  - LISTENER01
 
# Monitored channels.
channels:
 - MANAGEMENT.CHANNEL